sudo: false
dist: trusty

language: go

os:
  - linux

go:
  - "1.11.x"

install: true

env:
  global:
    - GO111MODULE=on
    - GOFLAGS='-mod vendor'
    - PATH=${TRAVIS_BUILD_DIR}/bin:${PATH}

before_install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s v1.17.1

script:
  - golangci-lint run
  - make

    #after_success:
    #  - bash <(curl -s https://codecov.io/bash)
