sudo: 'required'

language: go
go:
  - 1.13.x

service:
  - 'docker'

script:
  - make all
  - make image

deploy:
  provider: releases
  api_key: $GITHUB_DEPLOY_TOKEN
  skip_cleanup: true
  file:
    - release/kdt-linux
    - release/kdt-windows
    - release/kdt-darwin
    - release/kdt-linux.sha256
    - release/kdt-windows.sha256
    - release/kdt-darwin.sha256
  draft: true
  on:
    tags: true
    branch: master

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
    docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD;
    make push-image;
    fi
