language: go
go:
  - 1.13.x

script:
  - export GO111MODULE=on
  - GOOS=linux GOARCH=amd64 go build -o kdt
  - sha256sum kdt > kdt.sha256 
  - GOOS=windows GOARCH=amd64 go build -o kdt.exe
  - sha256sum kdt.exe > kdt.exe.sha256 

deploy:
  provider: releases
  github_token: $GITHUB_DEPLOY_TOKEN
  file:
    - kdt
    - kdt.sha256
    - kdt.exe
    - kdt.exe.sha256
  skip_cleanup: true
  draft: true
  keep_history: true
  on:
    branch: master
