language: go
go:
  - 1.13.x

script:
  - make all

deploy:
  provider: releases
  api_key: $GITHUB_DEPLOY_TOKEN
  skip_cleanup: true
  file:
    - release/kdt-linux
    - release/kdt-windows
    - release/kdt-darwin
    - release/kdt-linux.sha256
    - release/kdt-windows.sha256
    - release/kdt-darwin.sha256
  draft: true
  on:
    branch: master
