name: Build and Release KDT

# Controls when the action will run. 
on:
  push:
    branches: [ feature/gh-actions-migration ] ## delete
  ##pull_request:
  ##  branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  push_to_registry:
    name: Build and KDT and push image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Build
        run: |
          make all
          ls -al

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          prerelease: false
          draft: true
          body: |
           Changes in release
           - this

      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag_name=  ${{ github.ref }}
          hub release edit $(find _release -type f -printf "-a %p ") -m "" "$tag_name"

      - name: Upload `get.sh`
        run: |
          echo "upload get.sh"
        
