name: Build and Release KDT

# Controls when the action will run. 
on:
  push:
    branches: [ feature/gh-actions-migration ] ## delete
  ##pull_request:
  ##  branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  push_to_registry:
    name: Build and KDT and push image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Build
        run: |
          make all
          ls -al

      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag_name="${GITHUB_REF##}"
          hub release edit $(find _release -type f -printf "-a %p ") -m "" -d "$tag_name"


          #- name: Push to GitHub Packages
          #  uses: docker/build-push-action@v1
          #  with: 
          #    username: ${{ github.actor }}
          #    password: ${{ secrets.GITHUB_TOKEN }}
          #    registry: docker.pkg.github.com
          #    repository: kondukto-io/kdt/kdt-cli
          #    tag_with_ref: true

      - name: Upload `get.sh`
        run: |
          echo "upload get.sh"
        
