name: Build and Release KDT

# Controls when the action will run. 
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  push_to_registry:
    name: Build and KDT and push image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Version
        run: |
          git fetch --prune --unshallow --tags
          echo GIT_TAG=$(git describe --tags --abbrev=0) >> $GITHUB_ENV 

      - name: Build
        run: |
          make all
          _release/kdt-linux version

      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.GIT_TAG }}
          release_name: Release ${{ env.GIT_TAG }}
          prerelease: false
          draft: true
          body: |
           Changes in release
           - this

      - name: Upload Release Assets
        id: upload-release-assets 
        uses: dwenegar/upload-release-assets@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}
          assets_path: ./_release/

      - name: Upload get.sh
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USER }}
          KEY: ${{ secrets.SSH_KEY }}
        with:
          source: ./get.sh
          target: ${{ secrets.SSH_REMOTE }}

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build docker image
        run: make image
     
      - name: Push to registry
        run: 
          docker push kondukto/kondukto-cli:${{ env.GIT_TAG }}
          docker push kondukto/kondukto-cli:latest
